#!/bin/bash
result=$(npm run cucumber 2> /dev/null)

# removing color codes
rawResult=$(sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g" <<< $result)

passCheck="1 scenario (1 failed)"

if [[ $rawResult == *$passCheck* ]]; then
  echo "PASS"
else
  echo "FAIL"
fi
